apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: getrand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: leehyojae99/getrand_userseivce:v1.09
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection-service
  namespace: getrand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-collection-service
  template:
    metadata:
      labels:
        app: data-collection-service
    spec:
      containers:
        - name: data-collection-service
          image: leehyojae99/getrand_datacollectionservice:v1.05
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: getrand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: leehyojae99/getrand_analysticservice:v1.01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
