apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: getrand
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: data-collection-service
  namespace: getrand
spec:
  selector:
    app: data-collection-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: getrand
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: LoadBalancer

  